/*
 * This source file was generated by the Gradle 'init' task
 */
package org.waveskimmer.plugins

import org.gradle.api.Plugin
import org.gradle.api.Project

@Suppress("Unused")
class UpdateVersionsPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("updateVersions", UpdateVersionsExtension::class.java)

        project.tasks.register("checkLibsForUpdates", CheckForUpdatesTask::class.java) { task ->
            task.group = "versioning"
            task.description =
                "Checks configured repositories for newer library versions and updates the TOML version catalog in place."
            task.tomlFiles.setFrom(extension.tomlFiles)
            task.artifactRepos.set(extension.artifactRepos)
            task.updateMajor.set(extension.updateMajor)
            task.updateMinor.set(extension.updateMinor)
            task.updatePatch.set(extension.updatePatch)
            task.allowPrelease.set(extension.allowPrelease)
            task.outputs.upToDateWhen { false }
        }
    }
}
