/*
 * This source file was generated by the Gradle 'init' task
 */
package org.waveskimmer.plugins

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.string.shouldContain
import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.io.path.createTempDirectory

class UpdateVersionsPluginFunctionalTest : FunSpec({

    lateinit var projectDir: File
    lateinit var buildFile: File
    lateinit var settingsFile: File

    beforeTest {
        projectDir = createTempDirectory().toFile()
        buildFile = projectDir.resolve("build.gradle.kts")
        settingsFile = projectDir.resolve("settings.gradle.kts")
    }

    afterTest {
        projectDir.deleteRecursively()
    }

    test("can run task") {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id("org.waveskimmer.update-versions")
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("greeting")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        result.output shouldContain "Hello from plugin 'org.example.greeting'"
    }
})
