/*
 * This source file was generated by the Gradle 'init' task
 */
package org.waveskimmer.plugins

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.string.shouldContain
import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.io.path.Path
import kotlin.io.path.createDirectory
import kotlin.io.path.div
import kotlin.io.path.exists

class UpdateVersionsPluginFunctionalTest : FunSpec({

    lateinit var projectDir: File
    lateinit var buildFile: File
    lateinit var settingsFile: File
    lateinit var tomlFile: File

    beforeTest {
        val projectPath = Path("/tmp/simple-gradle")
        if (!projectPath.exists()) projectPath.createDirectory()
        val gradleDir = projectPath / "gradle"
        if (!gradleDir.exists()) gradleDir.createDirectory()

        projectDir = projectPath.toFile()
        buildFile = projectDir.resolve("build.gradle.kts")
        settingsFile = projectDir.resolve("settings.gradle.kts")
        tomlFile = projectDir.resolve("gradle/libs.versions.toml")
    }

    afterTest {
//        projectDir.deleteRecursively()
    }

    test("can run task") {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id("org.waveskimmer.update-versions")
            }
            
            dependencies { 
               testImplementation("org.slf4j:slf4j-simple:1.7.35")
            }
        """.trimIndent())
        tomlFile.writeText(
            """
            [versions] 
            slf4j = "1.7.35"
            
            [libraries]
            slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
        """.trimIndent()
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("checkLibsForUpdates")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        result.output shouldContain "Hello from plugin 'org.example.greeting'"
    }
})
